version: "3"
services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "9000:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    links:
      - dbmysql

  dbmysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "littlebluebag"
      MYSQL_USER: "littlebluebag"
      MYSQL_PASSWORD: "lbb123"
      MYSQL_ROOT_PASSWORD: "lbb123"
      MYSQL_ROOT_HOST: "localhost"
    volumes:
      - littlebluebag:/var/lib/mysql

volumes:
  littlebluebag:




