version: "3"
services:
  dbmysql:
    image: mysql/mysql-server:5.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "littlebluebag"
      MYSQL_USER: "littlebluebag"
      MYSQL_PASSWORD: "lbb123"
      MYSQL_ROOT_PASSWORD: "lbb123"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - littlebluebag:/var/lib/mysql
volumes:
  littlebluebag:
